--- 
- 
  name: "Stop bahmni-lab"
  service: "name=bahmni-lab state=stopped"
- 
  command: "yum list installed bahmni-lab"
  ignore_errors: true
  name: "Check if bahmni-lab rpm needs an update"
  register: installed_bahmni_lab
- 
  name: "Uninstall bahmni-lab rpm"
  when: "installed_bahmni_lab.stdout.find(\"{{ bahmni_lab_version }}\") == -1"
  yum: "name=\"bahmni-lab\" state=absent"
- 
  name: "Add bahmni-lab repository"
  yum_repository: 
    baseurl: "https://s3.ap-south-1.amazonaws.com/ocg-repos/lab_artifacts/bahmni-lab-89-84.noarch.rpm"
    description: "Bahmni-lab repo build internally"
    name: bahmni-lab-89-84.noarch.rpm
    state: present
