- name: Stop bahmni-lab
  service:
    name=bahmni-lab
    state=stopped
  when: passive is not defined or passive != 'yes'

- name: Download bahmni-lab yum repo rpm if not present
  get_url:
    url: http://s3.ap-south-1.amazonaws.com/ocb-repos/lab_artifacts/bahmni-lab-89-86.noarch.rpm
    dest: /tmp/bahmni-lab-89-86.noarch.rpm
    force: yes
