---
-
  name: "Stop bahmni-lab"
  service: "name=bahmni-lab state=stopped"
  ignore_errors: yes

-
  name: "Uninstall bahmni-lab rpm"
  yum: name=bahmni-lab state=absent

- name: Install bahmni-lab yum repository
  yum: name=/tmp/bahmni-lab-90.noarch.rpm state=present

- name: "Start bahmni-lab"
  service: "name=bahmni-lab state=started"
