---

- name: "Stop the bahmni-lab service"
  service:
    name: bahmni-lab
    state: stopped
  ignore_errors: yes

- name: "Uninstall the bahmni-lab rpm"
  yum:
    name: bahmni-lab
    state: absent

- name: Install custom bahmni-lab rpm
  yum:
    name: /tmp/bahmni-lab-90.noarch.rpm
    state: present

- name: "Start the bahmni-lab service"
  service:
    name: bahmni-lab
    state: started
