--- 
- 
  name: "Stop bahmni-lab"
  service: "name=bahmni-lab state=stopped"
- 
  command: "yum list installed bahmni-lab"
  ignore_errors: true
  name: "Check if bahmni-lab rpm needs an update"
  register: installed_bahmni_lab
- 
  name: "Uninstall bahmni-lab rpm"
  when: "installed_bahmni_lab.stdout.find(\"{{ bahmni_lab_version }}\") == -1"
  yum: "name=\"bahmni-lab\" state=absent"

- name: Download bahmni-lab yum repo rpm if not present
  get_url:
    url: http://s3.ap-south-1.amazonaws.com/ocb-repos/lab_artifacts/bahmni-lab-89-89.noarch.rpm
    dest: /tmp/bahmni-lab-89-87.noarch.rpm
    force: yes

- name: Install bahmni-lab yum repository
  yum: name=/tmp/bahmni-lab-89-87.noarch.rpm state=present
  
- name: "Start bahmni-lab"
  service: "name=bahmni-lab state=started"
