--- 
- 
  name: "Stop openmrs"
  service: "name=openmrs state=stopped"
  when: "passive is not defined or passive != 'yes'"
- 
  get_url: "url={{ bahmni_omod_url }} force=yes dest=/opt/openmrs/modules/ owner={{ bahmni_user }} group={{ bahmni_group }} mode=755"
  name: "Download omod file for bahmni-core omod"
- 
  get_url: "url={{ bahmniapps_url }} force=yes dest=/opt/bahmni-web/etc/bahmniapps.zip mode=0755"
  name: "Get bahmniapps from remote location if configured"
  when: "bahmniapps_url is defined"
- 
  command: "unlink /var/www/bahmniapps"
  name: "unlinking /var/www/bahmniapps"
  when: "bahmniapps_url is defined"
- 
  name: "Unzip downloaded bahmniapps file"
  unarchive: 
    dest: /opt/bahmni-web/etc/bahmniapps
    src: /opt/bahmni-web/etc/bahmniapps.zip
- 
  command: "ln -s /opt/bahmni-web/etc/possible-bahmniapps /var/www/bahmniapps"
  name: "linking /var/www/bahmniapps to Possible bahmniapps"
  when: "bahmniapps_url is defined"
- 
  name: "Start openmrs"
  service: "name=openmrs state=started"
  when: "passive is not defined or passive != 'yes'"
