- name: Stop openmrs
  service:
    name=openmrs
    state=stopped
  when: passive is not defined or passive != 'yes'

- name: Download omod file for bahmni-core omod
  get_url:
    url={{ bahmni_omod_url }}
    force=yes
    dest=/opt/openmrs/modules/
    owner={{ bahmni_user }}
    group={{ bahmni_group }}
    mode=755

- name: Get bahmniapps from remote location if configured
  get_url: url={{ bahmniapps_url }}
   force=yes
   dest=/opt/bahmni-web/etc/bahmniapps.zip
   mode=0755
  when: bahmniapps_url is defined

- name: Unzip downloaded bahmniapps file
  unarchive:
    src: /opt/bahmni-web/etc/bahmniapps.zip
    dest: /opt/bahmni-web/etc/bahmniapps
    when: bahmniapps_url is defined
    
- name: linking /var/www/bahmniapps to Possible bahmniapps
  command: ln -s /opt/bahmni-web/etc/bahmniapps /var/www/bahmniapps
  when: bahmniapps_url is defined

- name: Start openmrs
  service:
    name=openmrs
    state=started
  when: passive is not defined or passive != 'yes'
