---
-
  name: "Stop openmrs"
  service: "name=openmrs state=stopped"
  when: "passive is not defined or passive != 'yes'"

-
  command: "cp /tmp/bahmnicore-omod-0.90-SNAPSHOT.omod /opt/openmrs/modules"
  name: "copying the bahmnicore omod"
-
  command: "cp /tmp/bahmniapps.zip /opt/bahmni-web/etc/bahmniapps.zip"
  name: "copying the bahmni apps"
-
  command: "unlink /var/www/bahmniapps"
  name: "unlinking /var/www/bahmniapps"
  when: "bahmniapps_url is defined"
-
  name: "Unzip downloaded bahmniapps file"
  unarchive:
    dest: /opt/bahmni-web/etc/bahmniapps
    src: /opt/bahmni-web/etc/bahmniapps.zip
-
  command: "ln -s /opt/bahmni-web/etc/bahmniapps /var/www/bahmniapps"
  name: "linking /var/www/bahmniapps to Possible bahmniapps"
  when: "bahmniapps_url is defined"
-
  name: "Start openmrs"
  service: "name=openmrs state=started"
  when: "passive is not defined or passive != 'yes'"
-
  get_url: "url={{ id_gen_url }} force=yes dest=/etc/bahmni-installer/ owner={{ bahmni_user }} group={{ bahmni_group }} mode=755"
  name: "Download Id generation script file for bahmni Registration ID"

