--- 

- name: "Stop openmrs"
  service: "name=openmrs state=stopped"
  when: "passive is not defined or passive != 'yes'"
  
- name: "delete previous bahmnicore module"
  file: 
    path: /opt/openmrs/modules/bahmnicore-0.90.SNAPSHOT.omod
    state: absent
- name: "copying the bahmnicore omod"
  command: "cp /tmp/bahmnicore-0.90-SNAPSHOT.omod /opt/openmrs/modules/bahmnicore-0.90-SNAPSHOT.omod"

- name: "copying the bahmni apps"
  command: "cp /tmp/bahmniapps.zip /opt/bahmni-web/etc/bahmniapps.zip"

- name: "unlinking /var/www/bahmniapps"
  command: "unlink /var/www/bahmniapps"
  when: "bahmniapps_url is defined"

- name: "Unzip downloaded bahmniapps file"
  unarchive: 
    dest: /opt/bahmni-web/etc/bahmniapps
    src: /opt/bahmni-web/etc/bahmniapps.zip

- name: "linking /var/www/bahmniapps to Possible bahmniapps"
  command: "ln -s /opt/bahmni-web/etc/bahmniapps /var/www/bahmniapps"
  when: "bahmniapps_url is defined"

- name: Stop bahmni-reports
  service:
    name: bahmni-reports
    state: stopped

- name: Check if bahmnireports is already put in place
  stat:
    path: /tmp/bahmnireports.war
  register: bahmni_reports_stat_result

- name: download bahmnireports war file
  get_url:
    url:  https://s3.ap-south-1.amazonaws.com/ocb-repos/bahmnireports.war
    dest: /tmp/bahmnireports.war
  when: not (bahmni_reports_stat_result.stat.exists|bool)

- name: 'Unzip downloaded bahmnireports.war file'
  unarchive:
    dest: /opt/bahmni-reports/bahmni-reports
    src: /tmp/bahmnireports.war

- name: Start bahmni-reports
  service:
    name: bahmni-reports
    state: started

- name: "Linking configuration folder for Initializer module"
  file: 
    dest: /opt/openmrs/configuration
    group: bahmni
    mode: 644
    owner: bahmni
    src: /var/www/bahmni_config/openmrs/custom/
    state: link

- name: "Install initializer module"
  copy: 
    dest: /opt/openmrs/modules/initializer-1.0.1-SNAPSHOT.omod
    group: bahmni
    mode: "u=rw,g=r,o=r"
    owner: bahmni
    src: /tmp/initializer-1.0.1-SNAPSHOT.omod

- name: "Start openmrs"
  service: "name=openmrs state=started"
  when: "passive is not defined or passive != 'yes'"

- name: "copy yearly id script for bahmni Registration ID"
  copy:
    src: "{{ role_path }}/files/idGen.sh"
    dest: "/etc/bahmni-installer/idGen.sh"
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"
    mode: 755

- name: Configure yearly id cronjob
  cron:
    name: yearly_id_change
    special_time: "yearly"
    job: "/etc/bahmni-installer/idGen.sh"
