--- 
- 
  name: "Stop openmrs"
  service: "name=openmrs state=stopped"
  when: "passive is not defined or passive != 'yes'"
- 
  file: 
    path: /opt/openmrs/modules/bahmnicore-0.90.SNAPSHOT.omod
    state: absent
  name: "delete previous bahmnicore module"
- 
  command: "cp /tmp/bahmnicore-0.90-SNAPSHOT.omod /opt/openmrs/modules/bahmnicore-0.90-SNAPSHOT.omod"
  name: "copying the bahmnicore omod"
- 
  command: "cp /tmp/bahmniapps.zip /opt/bahmni-web/etc/bahmniapps.zip"
  name: "copying the bahmni apps"
- 
  command: "unlink /var/www/bahmniapps"
  name: "unlinking /var/www/bahmniapps"
  when: "bahmniapps_url is defined"
- 
  name: "Unzip downloaded bahmniapps file"
  unarchive: 
    dest: /opt/bahmni-web/etc/bahmniapps
    src: /opt/bahmni-web/etc/bahmniapps.zip
- 
  command: "ln -s /opt/bahmni-web/etc/bahmniapps /var/www/bahmniapps"
  name: "linking /var/www/bahmniapps to Possible bahmniapps"
  when: "bahmniapps_url is defined"
-
  service:
    name: bahmni-reports
    state: stopped

- name: download bahmnireports war file
  get_url:
    url:  https://s3.ap-south-1.amazonaws.com/ocb-repos/bahmnireports.war
    dest: /opt/bahmni-reports/
-
  name: 'Unzip downloaded bahmnireports.war file'
  unarchive:
    dest: /opt/bahmni-reports/bahmni-reports
    src: /opt/bahmni-reports/bahmnireports.war
-
  service:
    name: bahmni-reports
    state: started
- 
  file: 
    dest: /opt/openmrs/configuration
    group: bahmni
    mode: 644
    owner: bahmni
    src: /var/www/bahmni_config/openmrs/custom/
    state: link
  name: "Linking configuration folder for Initializer module"
- 
  copy: 
    dest: /opt/openmrs/modules/initializer-1.0.1-SNAPSHOT.omod
    group: bahmni
    mode: "u=rw,g=r,o=r"
    owner: bahmni
    src: /tmp/initializer-1.0.1-SNAPSHOT.omod
  name: "Install initializer module"
- 
  name: "Start openmrs"
  service: "name=openmrs state=started"
  when: "passive is not defined or passive != 'yes'"

- name: "copy yearly id script for bahmni Registration ID"
  copy:
    src: "{{ role_path }}/files/idGen.sh"
    dest: "/etc/bahmni-installer/idGen.sh"
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"
    mode: 755

- name: Configure yearly id cronjob
  cron:
    name: yearly_id_change
    special_time: "yearly"
    job: "/etc/bahmni-installer/idGen.sh"

