update concept_name set name ='Immédiatement' where name='Immediately' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='1 fois par jour' where name='Once a day' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='2 fois par jour' where name='Twice a day' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='3 fois par jour' where name='Thrice a day' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='4 fois par jour' where name='Four times a day' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque heure' where name='Every Hour' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 2 heures' where name='Every 2 hours' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 3 heures' where name='Every 3 hours' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 4 heures' where name='Every 4 hours' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 6 heures' where name='Every 6 hours' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 8 heures' where name='Every 8 hours' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 12 heures' where name='Every 12 hours' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='En alternant les jours' where name='On alternate days' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='1 fois la semaine' where name='Once a week' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='2 fois la semaine' where name='Twice a week' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='3 fois la semaine' where name='Thrice a week' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 2 semaines' where name='Every 2 weeks' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Chaque 3 semaines' where name='Every 3 weeks' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Une fois le mois' where name='Once a month' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='5 fois le jour' where name='Five times a day' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='4 fois la semaine' where name='Four days a week' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='5 fois la semaine' where name='Five days a week' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='6 fois la semaine' where name='Six days a week' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Jour(s)' where name='Day(s)' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Semaine(s)' where name='Week(s)' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Mois(s)' where name='Month(s)' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Avant le repas' where name='Before meals' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Estomac vide' where name='Empty stomach' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Après le repas' where name='After meals' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Le matin' where name='In the morning' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Le soir' where name='In the evening' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Avant de dormir' where name='At bedtime' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Immédiatement' where name='Immediately' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
update concept_name set name ='Tel que préscrit' where name='As directed' and locale= 'fr' and concept_name_type='FULLY_SPECIFIED' and voided = 0;
