				set @concept_id = 0;
                set @concept_short_id = 0;
                set @concept_full_id = 0;
                set @count = 0;
                

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ampoule injectable','Ampoule injectable','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Collyre','Collyre','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Comprimé','Comprimé','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Comprimé vaginale','Comprimé vaginale','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Crème à usage externe','Crème à usage externe','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cuillerée à soupe','Cuillerée à soupe','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Flacon injectable','Flacon injectable','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Gel à usage externe','Gel à usage externe','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Géllule','Géllule','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Lotion à usage externe','Lotion à usage externe','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pate','Pate','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Poche souple','Poche souple','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pomade à usage externe','Pomade à usage externe','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Poudre en boite','Poudre en boite','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Poudre en sachet et en boite','Poudre en sachet et en boite','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sachet','Sachet','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Solution','Solution','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Solution à usage externe','Solution à usage externe','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Solution enterale','Solution enterale','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tube à usage externe','Tube à usage externe','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Unité','Unité','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Solution (Inhallation)','Solution (Inhallation)','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Comprimé (Inhallation)','Comprimé (Inhallation)','N/A','Misc',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Géllule (Prefusion)','Géllule (Prefusion)','N/A','Misc',false);
