                set @concept_id = 0;
                set @concept_short_id = 0;
                set @concept_full_id = 0;
                set @count = 0;
 
                
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABACAVIR sulfate (ABC)','ABACAVIR sulfate (ABC)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC','ABC','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ACICLOVIR','ACICLOVIR','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Acide ACETYLSALICYLIQUE (aspirine)','Acide ACETYLSALICYLIQUE (aspirine)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Acide FOLIQUE','Acide FOLIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ACIDE TRANEXAMIQUE','ACIDE TRANEXAMIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AL 20/120 mg','AL 20/120 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ALBENDAZOLE','ALBENDAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ALUMINIUM','ALUMINIUM','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMITRIPTYLINE','AMITRIPTYLINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMOXICILLINE 125mg/ ac.CLAV','AMOXICILLINE 125mg/ ac.CLAV','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMOXICILLINE 500 mg / ac. CLAVULANIQUE','AMOXICILLINE 500 mg / ac. CLAVULANIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMOXICILLINE','AMOXICILLINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AS 100 mg / AQ éq. 270 mg base','AS 100 mg / AQ éq. 270 mg base','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AS 25 mg / AQ éq. 67.5 mg base','AS 25 mg / AQ éq. 67.5 mg base','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AS 50 mg / AQ éq. 135 mg base','AS 50 mg / AQ éq. 135 mg base','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ATENOLOL','ATENOLOL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ATV 300 mg / r 100 mg, comp.','ATV 300 mg / r 100 mg, comp.','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZITHROMYCINE','AZITHROMYCINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT','AZT','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BISACODYL','BISACODYL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BUTYLBROMURE HYOSCINE (butylbromure scopolamine)','BUTYLBROMURE HYOSCINE (butylbromure scopolamine)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CEFIXIME','CEFIXIME','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CHLORPHENAMINE','CHLORPHENAMINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CHLORPROMAZINE','CHLORPROMAZINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CIPROFLOXACINE','CIPROFLOXACINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CLINDAMYCINE','CLINDAMYCINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CLOXACILLINE','CLOXACILLINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CODEINE','CODEINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'COTRIMOXAZOLE','COTRIMOXAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CYCLOSERINE','CYCLOSERINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DAPSONE','DAPSONE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DARUNAVIR éthanolate (DRV)','DARUNAVIR éthanolate (DRV)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DIAZEPAM','DIAZEPAM','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DIDANOSINE (ddI)','DIDANOSINE (ddI)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DIGOXINE','DIGOXINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DOLUTEGRAVIR sodium (DTG)','DOLUTEGRAVIR sodium (DTG)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DOXYCYCLINE sel','DOXYCYCLINE sel','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'E 275 mg','E 275 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'EFAVIRENZ (EFV ou EFZ)','EFAVIRENZ (EFV ou EFZ)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ENALAPRIL','ENALAPRIL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ERYTHROMYCINE','ERYTHROMYCINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ETHAMBUTOL','ETHAMBUTOL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FLUCONAZOLE','FLUCONAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FOLINATE de CALCIUM','FOLINATE de CALCIUM','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FUROSEMIDE','FUROSEMIDE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'GLIBENCLAMIDE','GLIBENCLAMIDE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'GLYCERYLE TRINITRATE','GLYCERYLE TRINITRATE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'GRISEOFULVINE','GRISEOFULVINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'H 150 mg / R 300 mg','H 150 mg / R 300 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'H 30 mg / R 60 mg','H 30 mg / R 60 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'H 30 mg / Z 150 mg / R 60 mg','H 30 mg / Z 150 mg / R 60 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'H 75 mg / R 150 mg','H 75 mg / R 150 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HALOPERIDOL','HALOPERIDOL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HYDROCHLOROTHIAZIDE','HYDROCHLOROTHIAZIDE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IBUPROFENE','IBUPROFENE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ISONIAZIDE (H)','ISONIAZIDE (H)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IVERMECTINE','IVERMECTINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LAMIVUDINE (3TC)','LAMIVUDINE (3TC)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LEVOFLOXACINE','LEVOFLOXACINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LEVONORGESTREL','LEVONORGESTREL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LOPERAMIDE','LOPERAMIDE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LPV / r 400/100mg/5ml','LPV / r 400/100mg/5ml','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LPV 100 mg / r 25 mg','LPV 100 mg / r 25 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LPV 200 mg / r 50 mg','LPV 200 mg / r 50 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'METFORMINE','METFORMINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'METHYLDOPA','METHYLDOPA','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'METOCLOPRAMIDE','METOCLOPRAMIDE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'METRONIDAZOLE','METRONIDAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MICONAZOLE','MICONAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MORPHINE','MORPHINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MULTIVITAMINES','MULTIVITAMINES','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NEVIRAPINE (NVP)','NEVIRAPINE (NVP)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NYSTATINE','NYSTATINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'OFLOXACINE','OFLOXACINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'OMEPRAZOLE','OMEPRAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PARACETAMOL','PARACETAMOL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PHENOBARBITAL','PHENOBARBITAL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PHENOXYMETHYLPENICILLINE','PHENOXYMETHYLPENICILLINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'POTASSIUM chlorure','POTASSIUM chlorure','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PRAZIQUANTEL','PRAZIQUANTEL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PREDNISOLONE','PREDNISOLONE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PRIMAQUINE','PRIMAQUINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PROMETHAZINE','PROMETHAZINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PYRAZINAMIDE (Z)','PYRAZINAMIDE (Z)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PYRIDOXINE','PYRIDOXINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PYRIMETHAMINE','PYRIMETHAMINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'QUININE','QUININE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'R 150 mg / H 75 mg / Z 400 mg','R 150 mg / H 75 mg / Z 400 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'RALTEGRAVIR potassique (RAL)','RALTEGRAVIR potassique (RAL)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'RESOMAL','RESOMAL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'RETINOL','RETINOL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'RITONAVIR (r)','RITONAVIR (r)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SALBUTAMOL sulfate','SALBUTAMOL sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SALBUTAMOL','SALBUTAMOL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'sel de FER','sel de FER','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SELS REHYDRATATION ORALE (SRO)','SELS REHYDRATATION ORALE (SRO)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SODIUM chlorure','SODIUM chlorure','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SPIRONOLACTONE','SPIRONOLACTONE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SULFADIAZINE','SULFADIAZINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF','TDF','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF 300 mg / FTC 200 mg','TDF 300 mg / FTC 200 mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TENOFOVIR DISOPROXIL fumarate','TENOFOVIR DISOPROXIL fumarate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'THIAMINE chlorhydrate (vitamine B1)','THIAMINE chlorhydrate (vitamine B1)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TRAMADOL chlorhydrate','TRAMADOL chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VALGANCICLOVIR chlorhydrate','VALGANCICLOVIR chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VALPROATE de SODIUM','VALPROATE de SODIUM','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ZIDOVUDINE (AZT)','ZIDOVUDINE (AZT)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ACIDE TRANEXAMIQUE','ACIDE TRANEXAMIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMOXICILLINE','AMOXICILLINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMPHOTERICINE B','AMPHOTERICINE B','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMPICILLINE','AMPICILLINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ARTEMETHER','ARTEMETHER','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ARTESUNATE','ARTESUNATE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ATROPINE sulfate','ATROPINE sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BENZATHINE BENZYLPENICILLINE','BENZATHINE BENZYLPENICILLINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BLEOMYCINE sulfate','BLEOMYCINE sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BUTYLBROMURE HYOSCINE','BUTYLBROMURE HYOSCINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CALCIUM GLUCONATE','CALCIUM GLUCONATE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CEFTRIAXONE sodique','CEFTRIAXONE sodique','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CHLORPROMAZINE','CHLORPROMAZINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'COTRIMOXAZOLE','COTRIMOXAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DEXAMETHASONE phosphate','DEXAMETHASONE phosphate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DIAZEPAM','DIAZEPAM','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DIGOXINE','DIGOXINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DOPAMINE chlorhydrate','DOPAMINE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'EAU pour injection','EAU pour injection','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'EPINEPHRINE (adrenaline) tartrate','EPINEPHRINE (adrenaline) tartrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FUROSEMIDE','FUROSEMIDE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'GENTAMICINE sulfate','GENTAMICINE sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'GLUCOSE hypertonique','GLUCOSE hypertonique','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HALOPERIDOL','HALOPERIDOL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HEPARINE SODIQUE','HEPARINE SODIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HYDROCORTISONE succinate sodique','HYDROCORTISONE succinate sodique','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'INSULINE ISOPHANE (NPH)','INSULINE ISOPHANE (NPH)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'INSULINE RAPIDE','INSULINE RAPIDE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KANAMYCINE sulfate','KANAMYCINE sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KETAMINE chlorhydrate','KETAMINE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LEVONORGESTREL','LEVONORGESTREL','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LIDOCAINE chlorhydrate','LIDOCAINE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MEDROXYPROGESTERONE acétate','MEDROXYPROGESTERONE acétate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'METOCLOPRAMIDE chlorhydrate','METOCLOPRAMIDE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'METRONIDAZOLE','METRONIDAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MORPHINE chlorhydrate','MORPHINE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NADROPARINE calcique','NADROPARINE calcique','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NALOXONE chlorhydrate','NALOXONE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'OMEPRAZOLE sodique','OMEPRAZOLE sodique','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ONDANSETRON chlorhydrate','ONDANSETRON chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PARACETAMOL (acétaminophène)','PARACETAMOL (acétaminophène)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'POTASSIUM chlorure','POTASSIUM chlorure','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PROMETHAZINE chlorhydrate','PROMETHAZINE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'QUININE dichlorhydrate','QUININE dichlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SODIUM BICARBONATE','SODIUM BICARBONATE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'STREPTOMYCINE sulfate','STREPTOMYCINE sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TRAMADOL chlorhydrate','TRAMADOL chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VINCRISTINE sulfate','VINCRISTINE sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'GLUCOSE','GLUCOSE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PLASMA SUBSTITUT','PLASMA SUBSTITUT','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'RINGER lactate','RINGER lactate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SODIUM chlorure','SODIUM chlorure','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VACCIN HEPATITE B','VACCIN HEPATITE B','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VACCIN TT (tétanos)','VACCIN TT (tétanos)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ACIDE BENZOIQUE','ACIDE BENZOIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ANTI HEMORROIDAIRE','ANTI HEMORROIDAIRE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BENZOATE DE BENZYLE','BENZOATE DE BENZYLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CALAMINE','CALAMINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CLOTRIMAZOLE','CLOTRIMAZOLE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'D.E.E.T.','D.E.E.T.','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HYDRO-ALCOOLIQUE','HYDRO-ALCOOLIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HYDROCORTISONE acétate','HYDROCORTISONE acétate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LIDOCAINE','LIDOCAINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LUBRIFIANT à usage général','LUBRIFIANT à usage général','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MICONAZOLE nitrate','MICONAZOLE nitrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'OXYDE DE ZINC','OXYDE DE ZINC','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PODOPHYLLOTOXINE','PODOPHYLLOTOXINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'POLYVIDONE IODEE','POLYVIDONE IODEE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SULFADIAZINE ARGENTIQUE','SULFADIAZINE ARGENTIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VASELINE','VASELINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ATROPINE sulfate','ATROPINE sulfate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TETRACYCLINE chlorhydrate','TETRACYCLINE chlorhydrate','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FORMULE INFANTILE','FORMULE INFANTILE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LAIT THERAPEUTIQUE','LAIT THERAPEUTIQUE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NUTRITION ENTERALE','NUTRITION ENTERALE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'RUTF','RUTF','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ETRAVIRINE (ETV)','ETRAVIRINE (ETV)','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'RIFABUTINE','RIFABUTINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF 300mg / 3TC 300mg / DTG 50mg','TDF 300mg / 3TC 300mg / DTG 50mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'INH 300mg/ PYRIDOXINE 25mg/ SMX 800mg / TMP 160mg','INH 300mg/ PYRIDOXINE 25mg/ SMX 800mg / TMP 160mg','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FLUCYTOSINE','FLUCYTOSINE','N/A','Drug',false);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FLUOXETINE chlorhydrate','FLUOXETINE chlorhydrate','N/A','Drug',false);
