set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;



call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CHK(IPDForm)','CHK','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'HGR RB','HGR RB','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CS Partenaire','CS Partenaire','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autre(IPDForm)','Autre','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'I','I','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'II','II','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'III','III','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IV','IV','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB Lam','TB Lam','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date_TB Lam','Date_TB Lam','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Xpert','Xpert','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CrAg LFA_Sang','CrAg LFA_Sang','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CrAg LFA_CSF','CrAg LFA_CSF','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Syphilis test rapide','Syphilis test rapide','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hep B test rapide','Hep B test rapide','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hb','Hb','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Glycémie(IPDForm)','Glycémie','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Créatine (µmol/l)','Créatine (µmol/l)','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDR Palu','TDR Palu','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Neurologique','Neurologique','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Diarrhée aigue','Diarrhée aigue','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Diarrhée chronique','Diarrhée chronique','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autres syndromes GI','Autres syndromes GI','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hematologique: anemie','Hematologique: anemie','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Psychiatrique','Psychiatrique','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Respiratoire','Respiratoire','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cardiaque','Cardiaque','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cutane','Cutane','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Génitale/STI','Génitale/STI','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Néphrologique','Néphrologique','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Urologique','Urologique','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Endocrine','Endocrine','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Orale(IPDForm)','Orale','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hépatite','Hépatite','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Disseminated TB','Disseminated TB','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Malaria(IPDForm)','Malaria','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autres(IPDForm)','Autres','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PF','PF','N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'No Tier','No Tier','Text','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date d\'admission','Date d\'admission','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Référé en IPD par(FOSA)','Référé en IPD par(FOSA)','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'FOSA de suivi ARV','FOSA de suivi ARV','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Syndrome d\'admission','Syndrome d\'admission','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Si autre, preciser','Si autre, preciser','Text','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Malade arrivé mort','Malade arrivé mort','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Infirmier en charge de l\'admission','Infirmier en charge de l\'admission','Text','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Medecin en charge de l\'admission','Medecin en charge de l\'admission','Text','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Stade OMS','Stade OMS','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SNC_Glasgow(/15)','SNC_Glasgow(/15)','Numeric','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type','Type','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Resultat','Resultat','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Resultat(Creatine)','Resultat(Creatine)','Text','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date(IPDForm)','Date','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Examen Physique á l\'admission','Examen Physique á l\'admission','N/A','ConvSet',true );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Test á l\'admission','Test á l\'admission','N/A','ConvSet',true );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Admission IPD Form','Admission IPD','N/A','Misc',true );
