set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission, Date d\'admission",'Date d\'admission','Date','Misc',false );

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission History ARV, Jamais ARV","Jamais ARV",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission History ARV, Sous ARV","Sous ARV",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission History ARV, ARV intérrompu","ARV intérrompu",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission If interrupted, Less than or Equal to 3 Months","<=3M",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission If interrupted, 3 Months to 6 Months","3M-6M",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission If interrupted, 6 Months to 12 Months","6M-12M",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission If interrupted, Greater Than 12 Months",">12M",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission ARV Line, 1ere ligne","1ere ligne",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission ARV Line, 2e Ligne","2e Ligne",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission ARV Line, 3e Ligne","3e Ligne",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Diagnosis Element, TB LAM","TB LAM",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Diagnosis Element, Xpert","Xpert",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Diagnosis Element, Radio Thorax","Radio Thorax",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Diagnosis Element, Echo abdominale","Echo abdominale",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Diagnosis Element, Symptômes","Symptômes",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Diagnosis Element, Autre","Autre",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission TB Type, Pulmonaire-Bactériologiquement confirmé","Pulmonaire-Bactériologiquement confirmé",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission TB Type, Pulmonaire-Cliniquement Confirmé","Pulmonaire-Cliniquement Confirmé",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission TB Type, Extrapulmonaire","Extrapulmonaire",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Prophylaxis, Cotrimoxazole","Cotrimoxazole",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Prophylaxis, Fluconazole","Fluconazole",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Prophylaxis, Isoniazid","Isoniazid",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Prophylaxis, Dapsone","Dapsone",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission WHO Phase, One","I",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission WHO Phase, Two","II",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission WHO Phase, Three","III",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission WHO Phase, Four","IV",'N/A','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"CS Mater KASAI","CS Mater KASAI",'N/A','Misc',false );

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Référé en IPD pour MPEC?','Référé en IPD pour MPEC?','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date admission','Date admission','Datetime','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date de sortie','Date de sortie','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Diagnostics de sortie','Diagnostics de sortie','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date diagnostic VIH','Date diagnostic VIH','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date Dernier CD4','Date Dernier CD4','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Valeur Dernier CD4 (cells/mm3)','Valeur Dernier CD4 (cells/mm3)','Numeric','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date CD4 Plus élévé','Date CD4 Plus élévé','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date Dernier CV','Date Dernier CV','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Valeur dernière CV(cells/mm3)','Valeur dernière CV(cells/mm3)','Numeric','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Histoire ARV','Histoire ARV','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Si interrompu','Si interrompu','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Ligne ARV en cours','Ligne ARV en cours','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Régime actuel','Régime actuel','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date début de la ligne','Date début de la ligne','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date début ARV','Date début ARV','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Avez-vous déjà arrêté les ARV pendant plus d\'un mois','Avez-vous déjà arrêté les ARV pendant plus d\'un mois','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, TB en cours de traitement à l\'admission','TB en cours de traitement à l\'admission','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Elements de diagnostic TB','Elements de diagnostic TB','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Date début anti-TB','Date début anti-TB','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Adhérence aux anti-TB','Adhérence aux anti-TB','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, TB Précédentes?','TB Précédentes?','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Année','Année','Date','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Type','Type','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Prophylaxie à l\'admission','Prophylaxie à l\'admission','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, Stade OMS','Stade OMS','Coded','Misc',false );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'IPD Admission, SNC Glasgow(/15)','SNC Glasgow(/15)','Numeric','Misc',false );

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Section, Hospitalisations antérieures","Hospitalisations antérieures",'N/A','ConvSet',true );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Section, Historique VIH","Historique VIH",'N/A','ConvSet',true );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Section, Histoire ARV","Histoire ARV",'N/A','ConvSet',true );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Section, Adherence ARV","Adherence ARV",'N/A','ConvSet',true );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Section, Historique TB","Historique TB",'N/A','ConvSet',true );
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,"IPD Admission Section, TB Précédentes","TB Précédentes",'N/A','ConvSet',true );
