set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Antécédents cliniques','Antécédents cliniques','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Infections Opportunistes', 'Infections Opportunistes','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Infections Opportunistes_année', 'Infections Opportunistes_année','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Informations TB', 'Informations TB','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type de TB', 'Type de TB','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Site TB', 'Site TB','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Traitement TB Antérieur', 'Traitement TB Antérieur','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Historique TB antérieur(si traité précédemment)', 'Historique TB antérieur(si traité précédemment)','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB Année de depistage', 'TB Année de depistage','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB résultat du traitement', 'TB résultat du traitement','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Prophylaxie', 'Prophylaxie','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date_Debut_Prophylaxie', 'Date_Debut_Prophylaxie','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date_Fin_Prophylaxie', 'Date_Fin_Prophylaxie','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Historique ARV', 'Historique ARV','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Historique ARV', 'Historique ARV','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ligne d\'ARV', 'Ligne d\'ARV','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ARV', 'ARV','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date début', 'Date début','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autre traitement','Autre traitement','text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autres Pathologies','Autres Pathologies','text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autre pathologies années','Autre pathologies années','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Allergies','Allergies','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Allérgie type de réaction','Allérgie type de réaction','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Allergies - medicaments','Allergies - medicaments','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Obstétricaux_Gestité','Obstétricaux_Gestité','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Obstétricaux_Parité','Obstétricaux_Parité','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Obstétricaux_Fausses_couches','Obstétricaux_Fausses_couches','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Chirurgicaux','Chirurgicaux','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Chirurgicaux_année','Chirurgicaux_année','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hématologique_transfusion_antérieures_nbre','Hématologique_transfusion_antérieures_nbre','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hématologique_transfusion_antérieures_années','Hématologique_transfusion_antérieures_années','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hématologique_Groupe_Sanguin','Hématologique_Groupe_Sanguin','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hématologique_Rhésus','Hématologique_Rhésus','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ac, Enfant','Enfant','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Poids Naissance','Poids Naissance','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type d\'accouchement','Type d\'accouchement','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Prématuré','Prématuré','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Si prémature, nombre de semaines','Si prémature, nombre de semaines','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Allaitement maternel','Allaitement maternel','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type d\'allaitement','Type d\'allaitement','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Vaccination','Vaccination','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date de vaccinatinon','Date de vaccinatinon','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Dose','Dose','Numeric','MISC',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type de vaccination','Type de vaccination','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Vitamine A','Vitamine A','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date prescription Vitamine A','Date prescription Vitamine A','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'PTME','PTME','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Mère sous ARV pendant la grossesse','Mère sous ARV pendant la grossesse','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Si oui, Nombre de mois','Si oui, Nombre de mois','Numeric','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Prophylaxie à l\'accouchement','Prophylaxie à l\'accouchement','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type de Prophylaxie','Type de Prophylaxie','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Dose de Prophylaxie','Dose de Prophylaxie','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Durée de Prophylaxie','Durée de Prophylaxie','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Prophylaxie après la naissance','Prophylaxie après la naissance','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Informations Vaccination','Vaccination','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Information Infections opportunistes','Information Infections opportunistes','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Informations Prophylaxie','Informations Prophylaxie','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Info Prophylaxie à l\'accouchement','Info Prophylaxie à l\'accouchement','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Info Prophylaxie après la naissance','Info Prophylaxie après la naissance','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Informations chirurgicales','Informations chirurgicales','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Informations allergies','Informations allergies','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Traitement Antérieur ARV','Traitement Antérieur ARV','Text','Misc',FALSE);