set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF/3TC/EFV', 'TDF/3TC/EFV','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF/3TC/NVP', 'TDF/3TC/NVP','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/NVP', 'AZT/3TC/NVP','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/EFV', 'AZT/3TC/EFV','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC/3TC/NVP', 'ABC/3TC/NVP','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC/3TC/EFV', 'ABC/3TC/EFV','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF/3TC/LPV/r', 'TDF/3TC/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF/3TC/ATV/r', 'TDF/3TC/ATV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/LPV/r', 'AZT/3TC/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/ATV/r', 'AZT/3TC/ATV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC/3TC/LPV/r', 'ABC/3TC/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC/3TC/ATV/r', 'ABC/3TC/ATV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/TDF/LPV/r', 'AZT/3TC/TDF/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF/3TC/LPV/r', 'TDF/3TC/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF/3TC/ATV/r', 'TDF/3TC/ATV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/LPV/r', 'AZT/3TC/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/ATV/r', 'AZT/3TC/ATV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC/3TC/LPV/r', 'ABC/3TC/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC/3TC/ATV/r', 'ABC/3TC/ATV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/TDF/LPV/r', 'AZT/3TC/TDF/LPV/r','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/ABC', 'AZT/3TC/ABC','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AZT/3TC/DRV/r/DTG', 'AZT/3TC/DRV/r/DTG','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TDF/3TC/DRV/r/DTG', 'TDF/3TC/DRV/r/DTG','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ABC/3TC/DRV/r/DTG', 'ABC/3TC/DRV/r/DTG','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Voie basse','Voie basse','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Césarienne','Césarienne','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Maternel','Maternel','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Artificiel','Artificiel','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Mixte','Mixte','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BCG','BCG','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VAT','VAT','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VAR','VAR','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'VPO','VPO','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'1ere','1ere','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'2e','2e','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'3e','3e','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'1ere alternative','1ere alternative','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'2e alternative','2e alternative','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'3e alternative','3e alternative','N/A','Misc',FALSE);