update concept_name set name = 'Infections Opportunistes année' where name = 'Infections Opportunistes_année'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Date Debut Prophylaxie' where name = 'Date_Debut_Prophylaxie'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Date Fin Prophylaxie' where name = 'Date_Fin_Prophylaxie'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Obstétricaux Gestité' where name = 'Obstétricaux_Gestité'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Obstétricaux Parité' where name = 'Obstétricaux_Parité'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Obstétricaux Fausses couches' where name = 'Obstétricaux_Fausses_couches'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Chirurgicaux année' where name = 'Chirurgicaux_année'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures nbre' where name = 'Hématologique_transfusion_antérieures_nbre'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures années' where name = 'Hématologique_transfusion_antérieures_années'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique Groupe Sanguin' where name = 'Hématologique_Groupe_Sanguin'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique Rhésus' where name = 'Hématologique_Rhésus'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
update concept_name set name = 'Infections Opportunistes année' where name = 'Infections Opportunistes_année'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Date Debut Prophylaxie' where name = 'Date_Debut_Prophylaxie'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Date Fin Prophylaxie' where name = 'Date_Fin_Prophylaxie'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Obstétricaux Gestité' where name = 'Obstétricaux_Gestité'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Obstétricaux Parité' where name = 'Obstétricaux_Parité'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Obstétricaux Fausses couches' where name = 'Obstétricaux_Fausses_couches'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Chirurgicaux année' where name = 'Chirurgicaux_année'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures nbre' where name = 'Hématologique_transfusion_antérieures_nbre'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures années' where name = 'Hématologique_transfusion_antérieures_années'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique Groupe Sanguin' where name = 'Hématologique_Groupe_Sanguin'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Hématologique Rhésus' where name = 'Hématologique_Rhésus'  and concept_name_type = 'SHORT' and locale = 'fr' and voided = 0;
update concept_name set name = 'Infections Opportunistes année' where name = 'Infections Opportunistes_année'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Date Debut Prophylaxie' where name = 'Date_Debut_Prophylaxie'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Date Fin Prophylaxie' where name = 'Date_Fin_Prophylaxie'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Obstétricaux Gestité' where name = 'Obstétricaux_Gestité'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Obstétricaux Parité' where name = 'Obstétricaux_Parité'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Obstétricaux Fausses couches' where name = 'Obstétricaux_Fausses_couches'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Chirurgicaux année' where name = 'Chirurgicaux_année'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures nbre' where name = 'Hématologique_transfusion_antérieures_nbre'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures années' where name = 'Hématologique_transfusion_antérieures_années'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique Groupe Sanguin' where name = 'Hématologique_Groupe_Sanguin'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique Rhésus' where name = 'Hématologique_Rhésus'  and concept_name_type = 'FULLY_SPECIFIED' and locale = 'en' and voided = 0;
update concept_name set name = 'Infections Opportunistes année' where name = 'Infections Opportunistes_année'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Date Debut Prophylaxie' where name = 'Date_Debut_Prophylaxie'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Date Fin Prophylaxie' where name = 'Date_Fin_Prophylaxie'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Obstétricaux Gestité' where name = 'Obstétricaux_Gestité'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Obstétricaux Parité' where name = 'Obstétricaux_Parité'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Obstétricaux Fausses couches' where name = 'Obstétricaux_Fausses_couches'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Chirurgicaux année' where name = 'Chirurgicaux_année'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures nbre' where name = 'Hématologique_transfusion_antérieures_nbre'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique transfusion antérieures années' where name = 'Hématologique_transfusion_antérieures_années'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique Groupe Sanguin' where name = 'Hématologique_Groupe_Sanguin'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;
update concept_name set name = 'Hématologique Rhésus' where name = 'Hématologique_Rhésus'  and concept_name_type = 'SHORT' and locale = 'en' and voided = 0;