set @concept_id = 0;
set @child1_concept_id = 0;
set @child2_concept_id = 0;
set @child3_concept_id = 0;
set @child4_concept_id = 0;
set @child5_concept_id = 0;
set @child6_concept_id = 0;
set @child7_concept_id = 0;
set @child8_concept_id = 0;
set @child9_concept_id = 0;
set @child10_concept_id = 0;
set @child11_concept_id = 0;
set @child12_concept_id = 0;
set @child13_concept_id = 0;
set @child14_concept_id = 0;
set @child15_concept_id = 0;
set @child16_concept_id = 0;
set @child17_concept_id = 0;
set @child18_concept_id = 0;
set @child19_concept_id = 0;
set @child20_concept_id = 0;
set @child21_concept_id = 0;
set @child22_concept_id = 0;
set @child23_concept_id = 0;
set @child24_concept_id = 0;
set @child25_concept_id = 0;
set @child26_concept_id = 0;
set @child27_concept_id = 0;
set @child28_concept_id = 0;
set @child29_concept_id = 0;
set @child30_concept_id = 0;
set @child31_concept_id = 0;
set @child32_concept_id = 0;
set @child33_concept_id = 0;
set @child34_concept_id = 0;
set @child35_concept_id = 0;
set @child36_concept_id = 0;
set @child37_concept_id = 0;
set @child38_concept_id = 0;
set @child39_concept_id = 0;
set @child40_concept_id = 0;
set @child41_concept_id = 0;
set @child42_concept_id = 0;
set @child43_concept_id = 0;
set @child44_concept_id = 0;
set @child45_concept_id = 0;
set @child46_concept_id = 0;
set @child47_concept_id = 0;
set @child48_concept_id = 0;
set @child49_concept_id = 0;
set @child50_concept_id = 0;
set @child51_concept_id = 0;
set @child52_concept_id = 0;
set @child53_concept_id = 0;
set @child54_concept_id = 0;
set @child55_concept_id = 0;
set @child56_concept_id = 0;
set @child57_concept_id = 0;
set @child58_concept_id = 0;
set @child59_concept_id = 0;
set @child60_concept_id = 0;
set @child61_concept_id = 0;
set @child62_concept_id = 0;
set @child63_concept_id = 0;
set @child64_concept_id = 0;
set @child65_concept_id = 0;
set @child66_concept_id = 0;
set @child67_concept_id = 0;
set @child68_concept_id = 0;
set @child69_concept_id = 0;
set @child70_concept_id = 0;
set @child71_concept_id = 0;
set @child72_concept_id = 0;
set @child73_concept_id = 0;
set @child74_concept_id = 0;
set @child75_concept_id = 0;
set @child76_concept_id = 0;
set @child77_concept_id = 0;
set @child78_concept_id = 0;
set @child79_concept_id = 0;
set @child80_concept_id = 0;
set @child81_concept_id = 0;
set @child82_concept_id = 0;
set @child83_concept_id = 0;
set @child84_concept_id = 0;
set @child85_concept_id = 0;
set @child86_concept_id = 0;
set @child87_concept_id = 0;
set @child88_concept_id = 0;
set @child89_concept_id = 0;
set @child90_concept_id = 0;
set @child91_concept_id = 0;
set @child92_concept_id = 0;
set @child93_concept_id = 0;
set @child94_concept_id = 0;
set @child95_concept_id = 0;
set @child96_concept_id = 0;
set @child97_concept_id = 0;
set @child98_concept_id = 0;
set @child99_concept_id = 0;
set @child100_concept_id = 0;
set @child101_concept_id = 0;

select concept_id into @concept_id from concept_name where name = 'Infections Opportunistes' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;

select concept_id into @child1_concept_id from concept_name where name = 'Candidose orale (muguet)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child2_concept_id from concept_name where name = 'Candidose oesophagienne – muguet oesophagien' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child3_concept_id from concept_name where name = 'Stomatite angulaire (chéilite)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child4_concept_id from concept_name where name = 'Ulcères aphteux (“aphtes”)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child5_concept_id from concept_name where name = 'Sarcome de Kaposi (SK)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child6_concept_id from concept_name where name = 'Gingivite nécrotique' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child7_concept_id from concept_name where name = 'Folliculite' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child8_concept_id from concept_name where name = 'Impétigo' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child9_concept_id from concept_name where name = 'Syphilis' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child10_concept_id from concept_name where name = 'Tuberculose cutanée' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child11_concept_id from concept_name where name = 'Mycobactérie atypique' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child12_concept_id from concept_name where name = 'Angiomatose bacillaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child13_concept_id from concept_name where name = 'Dermatophytose' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child14_concept_id from concept_name where name = 'Candidose' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child15_concept_id from concept_name where name = 'Infections fongiques profondes:' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child16_concept_id from concept_name where name = 'Cryptoccocose' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child17_concept_id from concept_name where name = 'Histoplasmose' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child18_concept_id from concept_name where name = 'Pénicilliose' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child19_concept_id from concept_name where name = 'Papillomavirus humain (HPV)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child20_concept_id from concept_name where name = 'Molluscum contagiosum' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child21_concept_id from concept_name where name = 'Herpes simplex' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child22_concept_id from concept_name where name = 'Cytomegalovirus' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child23_concept_id from concept_name where name = 'EBV: virus d\’Epstein-Barr' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child24_concept_id from concept_name where name = 'Gale' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child25_concept_id from concept_name where name = 'Xérodermie et ichthyoses' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child26_concept_id from concept_name where name = 'Dermatite séborrhéique' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child27_concept_id from concept_name where name = 'Éruption pruritique papulaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child28_concept_id from concept_name where name = 'Psoriasis' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child29_concept_id from concept_name where name = 'Eczéma atopique' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child30_concept_id from concept_name where name = 'Lymphome non-hodgkinien' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child31_concept_id from concept_name where name = 'Syndrome de Stevens-Johnson' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child32_concept_id from concept_name where name = 'Epidermolyse toxique' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child33_concept_id from concept_name where name = 'Éruption médicamenteuse locale ou accompagnée d\’éosinophilie et' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child34_concept_id from concept_name where name = 'symptômes systémiques' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child35_concept_id from concept_name where name = 'Éruptions lichenoïdes' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child36_concept_id from concept_name where name = 'Réactions photosensibles' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child37_concept_id from concept_name where name = 'Syndrome rétroviral aigu' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child38_concept_id from concept_name where name = 'Leucoplasie orale chevelue' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child39_concept_id from concept_name where name = 'Candidose vaginale' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child40_concept_id from concept_name where name = 'Psoriasis' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child41_concept_id from concept_name where name = 'Muguet oral' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child42_concept_id from concept_name where name = 'Psoriasis réfractaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child43_concept_id from concept_name where name = 'Hypersensibilité à la névirapine' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child44_concept_id from concept_name where name = 'Condylome acuminé' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child45_concept_id from concept_name where name = 'Teigne (tinea)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child46_concept_id from concept_name where name = 'Verrue vulgaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child47_concept_id from concept_name where name = 'Herpes simplex disséminé' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child48_concept_id from concept_name where name = 'Sarcome de Kaposi extensif' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child49_concept_id from concept_name where name = 'Pénicilliose cutanée' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child50_concept_id from concept_name where name = 'Herpes simplex: étendu et persistant' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child51_concept_id from concept_name where name = 'Cryptoccoque cutané' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child52_concept_id from concept_name where name = 'Molluscum géant' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child53_concept_id from concept_name where name = 'Cytomégalovirus disséminé' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child54_concept_id from concept_name where name = 'Ichthyose acquise' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child55_concept_id from concept_name where name = 'Angiome bacillaire (AB)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child56_concept_id from concept_name where name = 'Candidose cutanée' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child57_concept_id from concept_name where name = 'Condylomes (verrues)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child58_concept_id from concept_name where name = 'Dermatophytes (teignes)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child59_concept_id from concept_name where name = 'Éruption prurigineuse papuleuse (EPP)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child60_concept_id from concept_name where name = 'Folliculite éosinophile' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child61_concept_id from concept_name where name = 'Herpes Zoster (Zona)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child62_concept_id from concept_name where name = 'Psoriasis' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child63_concept_id from concept_name where name = 'Teigne' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child64_concept_id from concept_name where name = 'Varicelle' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child65_concept_id from concept_name where name = 'Xérosis (Ichthyose)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child66_concept_id from concept_name where name = 'Pneumonie communautaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child67_concept_id from concept_name where name = 'Pneumocystose (PCP)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child68_concept_id from concept_name where name = 'Pneumopathie interstitielle lymphoïde (LIP)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child69_concept_id from concept_name where name = 'Sarcome de Kaposi pulmonaire (SK)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child70_concept_id from concept_name where name = 'Neuropathie périphérique' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child71_concept_id from concept_name where name = 'Méningite bactérienne' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child72_concept_id from concept_name where name = 'Méningite à cryptoccoques' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child73_concept_id from concept_name where name = 'Toxoplasmose cérébrale' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child74_concept_id from concept_name where name = 'Encéphalopathie à VIH - démence' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child75_concept_id from concept_name where name = 'Dépression' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child76_concept_id from concept_name where name = 'Anxiété' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child77_concept_id from concept_name where name = 'Problèmes liés à l\’abus d\’alcool ou drogues' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child78_concept_id from concept_name where name = 'Trouble bipolaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child79_concept_id from concept_name where name = 'Psychose' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child80_concept_id from concept_name where name = 'Diarrhée Aigüe' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child81_concept_id from concept_name where name = 'Diarrhée Chronique' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child82_concept_id from concept_name where name = 'Douleur abdominale (sans diarrhée)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child83_concept_id from concept_name where name = 'Co-infection avec hépatite B' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child84_concept_id from concept_name where name = 'Co-infection avec hépatite C' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child85_concept_id from concept_name where name = 'Insuffisance rénale chronique (IRC)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child86_concept_id from concept_name where name = 'Néphropathie' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child87_concept_id from concept_name where name = 'Insuffisance rénale aiguë' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child88_concept_id from concept_name where name = 'Candidose vulvo-vaginale' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child89_concept_id from concept_name where name = 'Verrues génitales' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child90_concept_id from concept_name where name = 'Cancer du col de l\’utérus' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child91_concept_id from concept_name where name = 'Tuberculose bactériologiquement confirmée (TB+)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child92_concept_id from concept_name where name = 'Tuberculose cliniquement diagnostiquée (TB/C)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child93_concept_id from concept_name where name = 'Tuberculose - Abdominale' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child94_concept_id from concept_name where name = 'Tuberculose - Ganglionnaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child95_concept_id from concept_name where name = 'Tuberculose - Mal de pott' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child96_concept_id from concept_name where name = 'Tuberculose - Meningé (MTB)' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child97_concept_id from concept_name where name = 'Tuberculose - Miliaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child98_concept_id from concept_name where name = 'Tuberculose - Os et articulaire' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child99_concept_id from concept_name where name = 'Tuberculose - Pericardite' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child100_concept_id from concept_name where name = 'Tuberculose - Pleuresie' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;
select concept_id into @child101_concept_id from concept_name where name = 'Tuberculose - Poly-serosite' and concept_name_type = 'FULLY_SPECIFIED' and locale = 'fr' and voided = 0;

            call add_concept_answer(@concept_id, @child1_concept_id, 1);
            call add_concept_answer(@concept_id, @child2_concept_id, 2);
            call add_concept_answer(@concept_id, @child3_concept_id, 3);
            call add_concept_answer(@concept_id, @child4_concept_id, 4);
            call add_concept_answer(@concept_id, @child5_concept_id, 5);
            call add_concept_answer(@concept_id, @child6_concept_id, 6);
            call add_concept_answer(@concept_id, @child7_concept_id, 7);
            call add_concept_answer(@concept_id, @child8_concept_id, 8);
            call add_concept_answer(@concept_id, @child9_concept_id, 9);
            call add_concept_answer(@concept_id, @child10_concept_id, 10);
            call add_concept_answer(@concept_id, @child11_concept_id, 11);
            call add_concept_answer(@concept_id, @child12_concept_id, 12);
            call add_concept_answer(@concept_id, @child13_concept_id, 13);
            call add_concept_answer(@concept_id, @child14_concept_id, 14);
            call add_concept_answer(@concept_id, @child15_concept_id, 15);
            call add_concept_answer(@concept_id, @child16_concept_id, 16);
            call add_concept_answer(@concept_id, @child17_concept_id, 17);
            call add_concept_answer(@concept_id, @child18_concept_id, 18);
            call add_concept_answer(@concept_id, @child19_concept_id, 19);
            call add_concept_answer(@concept_id, @child20_concept_id, 20);
            call add_concept_answer(@concept_id, @child21_concept_id, 21);
            call add_concept_answer(@concept_id, @child22_concept_id, 22);
            call add_concept_answer(@concept_id, @child23_concept_id, 23);
            call add_concept_answer(@concept_id, @child24_concept_id, 24);
            call add_concept_answer(@concept_id, @child25_concept_id, 25);
            call add_concept_answer(@concept_id, @child26_concept_id, 26);
            call add_concept_answer(@concept_id, @child27_concept_id, 27);
            call add_concept_answer(@concept_id, @child28_concept_id, 28);
            call add_concept_answer(@concept_id, @child29_concept_id, 29);
            call add_concept_answer(@concept_id, @child30_concept_id, 30);
            call add_concept_answer(@concept_id, @child31_concept_id, 31);
            call add_concept_answer(@concept_id, @child32_concept_id, 32);
            call add_concept_answer(@concept_id, @child33_concept_id, 33);
            call add_concept_answer(@concept_id, @child34_concept_id, 34);
            call add_concept_answer(@concept_id, @child35_concept_id, 35);
            call add_concept_answer(@concept_id, @child36_concept_id, 36);
            call add_concept_answer(@concept_id, @child37_concept_id, 37);
            call add_concept_answer(@concept_id, @child38_concept_id, 38);
            call add_concept_answer(@concept_id, @child39_concept_id, 39);
            call add_concept_answer(@concept_id, @child40_concept_id, 40);
            call add_concept_answer(@concept_id, @child41_concept_id, 41);
            call add_concept_answer(@concept_id, @child42_concept_id, 42);
            call add_concept_answer(@concept_id, @child43_concept_id, 43);
            call add_concept_answer(@concept_id, @child44_concept_id, 44);
            call add_concept_answer(@concept_id, @child45_concept_id, 45);
            call add_concept_answer(@concept_id, @child46_concept_id, 46);
            call add_concept_answer(@concept_id, @child47_concept_id, 47);
            call add_concept_answer(@concept_id, @child48_concept_id, 48);
            call add_concept_answer(@concept_id, @child49_concept_id, 49);
            call add_concept_answer(@concept_id, @child50_concept_id, 50);
            call add_concept_answer(@concept_id, @child51_concept_id, 51);
            call add_concept_answer(@concept_id, @child52_concept_id, 52);
            call add_concept_answer(@concept_id, @child53_concept_id, 53);
            call add_concept_answer(@concept_id, @child54_concept_id, 54);
            call add_concept_answer(@concept_id, @child55_concept_id, 55);
            call add_concept_answer(@concept_id, @child56_concept_id, 56);
            call add_concept_answer(@concept_id, @child57_concept_id, 57);
            call add_concept_answer(@concept_id, @child58_concept_id, 58);
            call add_concept_answer(@concept_id, @child59_concept_id, 59);
            call add_concept_answer(@concept_id, @child60_concept_id, 60);
            call add_concept_answer(@concept_id, @child61_concept_id, 61);
            call add_concept_answer(@concept_id, @child62_concept_id, 62);
            call add_concept_answer(@concept_id, @child63_concept_id, 63);
            call add_concept_answer(@concept_id, @child64_concept_id, 64);
            call add_concept_answer(@concept_id, @child65_concept_id, 65);
            call add_concept_answer(@concept_id, @child66_concept_id, 66);
            call add_concept_answer(@concept_id, @child67_concept_id, 67);
            call add_concept_answer(@concept_id, @child68_concept_id, 68);
            call add_concept_answer(@concept_id, @child69_concept_id, 69);
            call add_concept_answer(@concept_id, @child70_concept_id, 70);
            call add_concept_answer(@concept_id, @child71_concept_id, 71);
            call add_concept_answer(@concept_id, @child72_concept_id, 72);
            call add_concept_answer(@concept_id, @child73_concept_id, 73);
            call add_concept_answer(@concept_id, @child74_concept_id, 74);
            call add_concept_answer(@concept_id, @child75_concept_id, 75);
            call add_concept_answer(@concept_id, @child76_concept_id, 76);
            call add_concept_answer(@concept_id, @child77_concept_id, 77);
            call add_concept_answer(@concept_id, @child78_concept_id, 78);
            call add_concept_answer(@concept_id, @child79_concept_id, 79);
            call add_concept_answer(@concept_id, @child80_concept_id, 80);
            call add_concept_answer(@concept_id, @child81_concept_id, 81);
            call add_concept_answer(@concept_id, @child82_concept_id, 82);
            call add_concept_answer(@concept_id, @child83_concept_id, 83);
            call add_concept_answer(@concept_id, @child84_concept_id, 84);
            call add_concept_answer(@concept_id, @child85_concept_id, 85);
            call add_concept_answer(@concept_id, @child86_concept_id, 86);
            call add_concept_answer(@concept_id, @child87_concept_id, 87);
            call add_concept_answer(@concept_id, @child88_concept_id, 88);
            call add_concept_answer(@concept_id, @child89_concept_id, 89);
            call add_concept_answer(@concept_id, @child90_concept_id, 90);
            call add_concept_answer(@concept_id, @child91_concept_id, 91);
            call add_concept_answer(@concept_id, @child92_concept_id, 92);
            call add_concept_answer(@concept_id, @child93_concept_id, 93);
            call add_concept_answer(@concept_id, @child94_concept_id, 94);
            call add_concept_answer(@concept_id, @child95_concept_id, 95);
            call add_concept_answer(@concept_id, @child96_concept_id, 96);
            call add_concept_answer(@concept_id, @child97_concept_id, 97);
            call add_concept_answer(@concept_id, @child98_concept_id, 98);
            call add_concept_answer(@concept_id, @child99_concept_id, 99);
            call add_concept_answer(@concept_id, @child100_concept_id, 100);
            call add_concept_answer(@concept_id, @child101_concept_id, 101);