set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Extrapulmonaire','Extrapulmonaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pulmonaire','Pulmonaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Abdominale','Abdominale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ganglionnaire','Ganglionnaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Mal de pott','Mal de pott','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Meningé','Meningé','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Miliaire','Miliaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Os et articulaire','Os et articulaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pericardite','Pericardite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pleuresie','Pleuresie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Poly-serosite','Poly-serosite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Nouveau patient','Nouveau patient','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Traité précédemment','Traité précédemment','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Rechute','Rechute','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Traitement après echec','Traitement après echec','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Traitement après perdu de vue','Traitement après perdu de vue','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Guéri','Guéri','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Traitement terminé','Traitement terminé','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Échec','Échec','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Décédé','Décédé','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Perdu de vue','Perdu de vue','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Reféré','Reféré','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Non évalué','Non évalué','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Succès','Succès','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CTX','CTX','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Dapsone','Dapsone','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Fluconazole','Fluconazole','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'INH','INH','N/A','Misc',FALSE);