set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Candidose orale (muguet)','Candidose orale (muguet)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Candidose oesophagienne – muguet oesophagien','Candidose oesophagienne – muguet oesophagien','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Stomatite angulaire (chéilite)','Stomatite angulaire (chéilite)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ulcères aphteux (“aphtes”)','Ulcères aphteux (“aphtes”)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sarcome de Kaposi (SK)','Sarcome de Kaposi (SK)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Gingivite nécrotique','Gingivite nécrotique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Folliculite','Folliculite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Impétigo','Impétigo','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Syphilis','Syphilis','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose cutanée','Tuberculose cutanée','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Mycobactérie atypique','Mycobactérie atypique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Angiomatose bacillaire','Angiomatose bacillaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Dermatophytose','Dermatophytose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Candidose','Candidose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Infections fongiques profondes:','Infections fongiques profondes:','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cryptoccocose','Cryptoccocose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Histoplasmose','Histoplasmose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pénicilliose','Pénicilliose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Papillomavirus humain (HPV)','Papillomavirus humain (HPV)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Molluscum contagiosum','Molluscum contagiosum','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Herpes simplex','Herpes simplex','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cytomegalovirus','Cytomegalovirus','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'EBV: virus d\’Epstein-Barr','EBV: virus d\’Epstein-Barr','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Gale','Gale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Xérodermie et ichthyoses','Xérodermie et ichthyoses','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Dermatite séborrhéique','Dermatite séborrhéique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Éruption pruritique papulaire','Éruption pruritique papulaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Psoriasis','Psoriasis','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Eczéma atopique','Eczéma atopique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Lymphome non-hodgkinien','Lymphome non-hodgkinien','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Syndrome de Stevens-Johnson','Syndrome de Stevens-Johnson','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Epidermolyse toxique','Epidermolyse toxique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Éruption médicamenteuse locale ou accompagnée d\’éosinophilie et','Éruption médicamenteuse locale ou accompagnée d\’éosinophilie et' ,'N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'symptômes systémiques','symptômes systémiques','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Éruptions lichenoïdes','Éruptions lichenoïdes','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Réactions photosensibles','Réactions photosensibles','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Syndrome rétroviral aigu','Syndrome rétroviral aigu','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Leucoplasie orale chevelue','Leucoplasie orale chevelue','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Candidose vaginale','Candidose vaginale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Psoriasis','Psoriasis','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Muguet oral','Muguet oral','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Psoriasis réfractaire','Psoriasis réfractaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hypersensibilité à la névirapine','Hypersensibilité à la névirapine','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Condylome acuminé','Condylome acuminé','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Teigne (tinea)','Teigne (tinea)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Verrue vulgaire','Verrue vulgaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Herpes simplex disséminé','Herpes simplex disséminé','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sarcome de Kaposi extensif','Sarcome de Kaposi extensif','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pénicilliose cutanée','Pénicilliose cutanée','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Herpes simplex: étendu et persistant','Herpes simplex: étendu et persistant','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cryptoccoque cutané','Cryptoccoque cutané','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Molluscum géant','Molluscum géant','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cytomégalovirus disséminé','Cytomégalovirus disséminé','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ichthyose acquise','Ichthyose acquise','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Angiome bacillaire (AB)','Angiome bacillaire (AB)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Candidose cutanée','Candidose cutanée','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Condylomes (verrues)','Condylomes (verrues)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Dermatophytes (teignes)','Dermatophytes (teignes)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Éruption prurigineuse papuleuse (EPP)','Éruption prurigineuse papuleuse (EPP)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Folliculite éosinophile','Folliculite éosinophile','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Herpes Zoster (Zona)','Herpes Zoster (Zona)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Psoriasis','Psoriasis','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Teigne','Teigne','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Varicelle','Varicelle','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Xérosis (Ichthyose)','Xérosis (Ichthyose)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pneumonie communautaire','Pneumonie communautaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pneumocystose (PCP)','Pneumocystose (PCP)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pneumopathie interstitielle lymphoïde (LIP)','Pneumopathie interstitielle lymphoïde (LIP)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sarcome de Kaposi pulmonaire (SK)','Sarcome de Kaposi pulmonaire (SK)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Neuropathie périphérique','Neuropathie périphérique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Méningite bactérienne','Méningite bactérienne','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Méningite à cryptoccoques','Méningite à cryptoccoques','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Toxoplasmose cérébrale','Toxoplasmose cérébrale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Encéphalopathie à VIH - démence','Encéphalopathie à VIH - démence','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Dépression','Dépression','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Anxiété','Anxiété','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Problèmes liés à l\’abus d\’alcool ou drogues','Problèmes liés à l\’abus d\’alcool ou drogues','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Trouble bipolaire','Trouble bipolaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Psychose','Psychose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Diarrhée Aigüe','Diarrhée Aigüe','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Diarrhée Chronique','Diarrhée Chronique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Douleur abdominale (sans diarrhée)','Douleur abdominale (sans diarrhée)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Co-infection avec hépatite B','Co-infection avec hépatite B','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Co-infection avec hépatite C','Co-infection avec hépatite C','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Insuffisance rénale chronique (IRC)','Insuffisance rénale chronique (IRC)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Néphropathie','Néphropathie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Insuffisance rénale aiguë','Insuffisance rénale aiguë','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Candidose vulvo-vaginale','Candidose vulvo-vaginale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Verrues génitales','Verrues génitales','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cancer du col de l\’utérus','Cancer du col de l\’utérus','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose bactériologiquement confirmée (TB+)','Tuberculose bactériologiquement confirmée (TB+)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose cliniquement diagnostiquée (TB/C)','Tuberculose cliniquement diagnostiquée (TB/C)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Abdominale','Tuberculose - Abdominale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Ganglionnaire','Tuberculose - Ganglionnaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Mal de pott','Tuberculose - Mal de pott','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Meningé (MTB)','Tuberculose - Meningé (MTB)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Miliaire','Tuberculose - Miliaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Os et articulaire','Tuberculose - Os et articulaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Pericardite','Tuberculose - Pericardite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Pleuresie','Tuberculose - Pleuresie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose - Poly-serosite','Tuberculose - Poly-serosite','N/A','Misc',FALSE);