set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Paraclinique(form)','Paraclinique','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Paraclinique','Paraclinique','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type de radio','Type de radio','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date de radio','Date de radio','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Resultats Radio','Resultats Radio','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Echographie','Echographie','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Type d\'Echo','Type d\'Echo','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cardiaque','Cardiaque','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Abdominale','Abdominale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Abdomino Pelvienne','Abdomino Pelvienne','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autre(Paraform)','Autre','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pelvienne','Pelvienne','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autre Type d\’Echo','Autre Type d\’Echo','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date Echo','Date Echo','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Resultats Echo','Resultats Echo','Text','Misc',FALSE);
