call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Suivi Consultation','Suivi Consultation','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Motif Consultation','Motif Consultation','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Histoire Maladie Actuelle','Histoire Maladie Actuelle','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Stade clinique OMS','Stade clinique OMS','Coded','Misc',FALSE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Examen clinique','Examen clinique','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Etat general','Etat general','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Yeux','Yeux','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Bouche','Bouche','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ganglions Sites','Ganglions Sites','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Coeur','Coeur','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Poumon','Poumon','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Abdomen','Abdomen','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'App génito-urinaire','App génito-urinaire','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Peau','Peau','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'App. Genital','App. Genital','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'App. Osteoarticulaire','App. Osteoarticulaire','Text','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Neurologie','Neurologie','Text','Misc',FALSE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Information Diagnostique','Information Diagnostique','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sc, Diagnostic','Diagnostic','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Observations et conduite à tenir','Observations et conduite à tenir','Text','Misc',FALSE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sc, Informations Infections opportunistes','Informations Infections opportunistes','N/A','Misc',TRUE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Status IO','Status IO','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Nouveau', 'Nouveau','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'En Cours', 'En Cours','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Rechute', 'Rechute','N/A','Misc',FALSE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sc, Informations prophylaxie','Informations prophylaxie','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Prophylaxie','Prophylaxie','Coded','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date Debut Prophylaxie','Date Debut Prophylaxie','Coded','Misc',FALSE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Prochain RDV','Prochain RDV','N/A','Misc',TRUE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Date de prochain RDV','Date de prochain RDV','Date','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Notes','Notes','text','Misc',FALSE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'13. Conditions gastro-intestinales 213', '13. Conditions gastro-intestinales 213','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Abdomen aigue : apendicite, peritonite, …', 'Abdomen aigue : apendicite, peritonite, …','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Accident vasculaire cérébral (AVC) 12. Conditions psychiatriques 205', 'Accident vasculaire cérébral (AVC) 12. Conditions psychiatriques 205','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Amygdalite', 'Amygdalite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Anémie', 'Anémie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Asymptomatique', 'Asymptomatique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Autres effets secondaires dus aux ARV', 'Autres effets secondaires dus aux ARV','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Bronchite', 'Bronchite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Bubon inguinal', 'Bubon inguinal','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cancer du col', 'Cancer du col','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Candidose œsophagienne – muguet œsophagien', 'Candidose œsophagienne – muguet œsophagien','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cardiopathie', 'Cardiopathie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Carrie dentaire', 'Carrie dentaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Condylomes (Ano-génital)', 'Condylomes (Ano-génital)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Conjonctivite purulente chez le nouveau-né', 'Conjonctivite purulente chez le nouveau-né','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Cystite', 'Cystite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Diabète type 1 et type 2', 'Diabète type 1 et type 2','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Diarrhée lié au LPV/r ou autres médicaments', 'Diarrhée lié au LPV/r ou autres médicaments','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Douleur pelvienne ou sensibilité du col utérin chez la femme', 'Douleur pelvienne ou sensibilité du col utérin chez la femme','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'échec thérapeutique', 'échec thérapeutique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Écoulement urétral ou dysurie chez l’homme', 'Écoulement urétral ou dysurie chez l’homme','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Écoulement vaginal chez la femme (vaginite, cervicite)', 'Écoulement vaginal chez la femme (vaginite, cervicite)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Effets secondaire lié à l’EFV ou autres médicaments', 'Effets secondaire lié à l’EFV ou autres médicaments','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Epilepsie', 'Epilepsie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Éruption cutanée liée aux médicaments', 'Éruption cutanée liée aux médicaments','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Gastrite', 'Gastrite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Gastro-entérite aigue', 'Gastro-entérite aigue','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Grossesse (free text entry for details)', 'Grossesse (free text entry for details)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Herpes Simplex (VHS 1 & 2)', 'Herpes Simplex (VHS 1 & 2)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Hypertension artérielle', 'Hypertension artérielle','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Infection à MAC', 'Infection à MAC','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Insomnie', 'Insomnie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Insuffisance rénale chronique', 'Insuffisance rénale chronique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'L’agression sexuelle', 'L’agression sexuelle','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'La dépression', 'La dépression','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Laryngite', 'Laryngite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Le sarcome de Kaposi pulmonaire (SK)', 'Le sarcome de Kaposi pulmonaire (SK)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Malignité des poumons', 'Malignité des poumons','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'malnutrition modéré', 'malnutrition modéré','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'malnutrition sévère', 'malnutrition sévère','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Méningite à crypto coques', 'Méningite à crypto coques','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Méningite tuberculeuse (MTB)', 'Méningite tuberculeuse (MTB)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Méningite virale', 'Méningite virale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Néphropathie associée au VIH', 'Néphropathie associée au VIH','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Oesophagite', 'Oesophagite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Onychomycose', 'Onychomycose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ophtalmopathie (ex :Glaucome)', 'Ophtalmopathie (ex :Glaucome)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'otite11. Conditions neurologiques 181', 'otite11. Conditions neurologiques 181','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Paludisme', 'Paludisme','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Panaris', 'Panaris','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Papillomavirus humain (PVH)', 'Papillomavirus humain (PVH)','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Parasitose', 'Parasitose','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Péricardite TB', 'Péricardite TB','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pharyngite', 'Pharyngite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pied d\’athlète', 'Pied d\’athlète','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Plaies infectées', 'Plaies infectées','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pneumonie bactérienne', 'Pneumonie bactérienne','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pneumonie virale', 'Pneumonie virale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Psychose : le fonctionnel vs le psychiatrique', 'Psychose : le fonctionnel vs le psychiatrique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Pyélonéphrite', 'Pyélonéphrite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Rétinite à CMV', 'Rétinite à CMV','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Rhinite', 'Rhinite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sarcome de Kaposi', 'Sarcome de Kaposi','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Sinusite', 'Sinusite','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Stress Post Traumatique', 'Stress Post Traumatique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'suspicion échec thérapeutique', 'suspicion échec thérapeutique','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Syndrome grippal', 'Syndrome grippal','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB abdominale', 'TB abdominale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB disséminée', 'TB disséminée','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB ganglionnaire', 'TB ganglionnaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB méningée', 'TB méningée','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB osseuse', 'TB osseuse','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TB pleurale', 'TB pleurale','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Troubles hépatiques', 'Troubles hépatiques','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Tuberculose pulmonaire', 'Tuberculose pulmonaire','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ulcération génitale chez l\’homme ou chez la femme', 'Ulcération génitale chez l\’homme ou chez la femme','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Ulcère cutané', 'Ulcère cutané','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'Xérosis (Ichthyose) 1', 'Xérosis (Ichthyose) 1','N/A','Misc',FALSE);
