set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MANDALA ANSWOR Jeanine','MANDALA ANSWOR Jeanine','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BANONA KIFU  Nono','BANONA KIFU  Nono','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'OWANGA TAMBWE  Esther','OWANGA TAMBWE  Esther','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KALAMBA KABONGO  Christian','KALAMBA KABONGO  Christian','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MFUTISI Bibi  Judith','MFUTISI Bibi  Judith','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BARAKA MOLA ANNIE','BARAKA MOLA ANNIE','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KANYONA MBUYI LOUIS RICHARD','KANYONA MBUYI LOUIS RICHARD','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NGONDE ANNIE','NGONDE ANNIE','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KALWANGILA SEQUEIRA Tony','KALWANGILA SEQUEIRA Tony','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MUCINYA LUMOWO Gisèle','MUCINYA LUMOWO Gisèle','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TSHIMUNGU Alain','TSHIMUNGU Alain','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MANGANA Freddy','MANGANA Freddy','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KALENGAY Corine','KALENGAY Corine','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KABEMA Antoine','KABEMA Antoine','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'AMSINI Chicco','AMSINI Chicco','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NTABUGI Nadine','NTABUGI Nadine','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MBUNGA','MBUNGA','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KAYEMBE Kick','KAYEMBE Kick','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KISAKA Patrick','KISAKA Patrick','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MWASOMI Patrick','MWASOMI Patrick','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'WALLAYS Elisabeth','WALLAYS Elisabeth','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MBUAYA Joelle','MBUAYA Joelle','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NYALENGE Destin','NYALENGE Destin','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MUNZIKA EVA','MUNZIKA EVA','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MBALA ALEXIS','MBALA ALEXIS','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NGANDU ROBERT','NGANDU ROBERT','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SHAKO LISETTE','SHAKO LISETTE','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'LUKELO CECILE','LUKELO CECILE','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MPOYI EMMANUEL','MPOYI EMMANUEL','N/A','Misc',FALSE);

call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'WALO Chadrack','WALO Chadrack','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MOLAY Gaylord','MOLAY Gaylord','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KALALA MUKENA Serge','KALALA MUKENA Serge','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BELANGANAY Geoffrey','BELANGANAY Geoffrey','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KOMOYO Gertrude','KOMOYO Gertrude','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'DUQUET Katrien','DUQUET Katrien','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CIBANGU Jean de Dieu','CIBANGU Jean de Dieu','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BAFINDA Phillipe','BAFINDA Phillipe','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BANINGIME Sandrine','BANINGIME Sandrine','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'ILUNGA BONDO Michel','ILUNGA BONDO Michel','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NUMELIE ILUNGA Thérèse','NUMELIE ILUNGA Thérèse','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BUMBANGI Serge','BUMBANGI Serge','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MALUNGIDI Pelagie','MALUNGIDI Pelagie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MBALA SEKI Alexis','MBALA SEKI Alexis','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KUTUKUENDA NZADI Roger','KUTUKUENDA NZADI Roger','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NTUMBA Naomie','NTUMBA Naomie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SONGO Carmen','SONGO Carmen','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KAYEMBE Sylvain','KAYEMBE Sylvain','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KUKANGIDILA Emmanuel','KUKANGIDILA Emmanuel','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NSEKI Patrick','NSEKI Patrick','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KUSAKANA Eveline','KUSAKANA Eveline','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MBUALA Prodige','MBUALA Prodige','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NSUNDA NTANGU Afrie','NSUNDA NTANGU Afrie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KAMUNGA Kennedy','KAMUNGA Kennedy','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'MUJINGILA Fanny','MUJINGILA Fanny','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'NIAMA Despy','NIAMA Despy','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'KALONJI Euphrasie','KALONJI Euphrasie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'BATUMBA John','BATUMBA John','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'CIMANGA Nelly','CIMANGA Nelly','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'SHALASHALA Valerie','SHALASHALA Valerie','N/A','Misc',FALSE);
call add_concept_fr(@concept_id,@concept_short_id,@concept_full_id,'TAMBWE Mike','TAMBWE Mike','N/A','Misc',FALSE);
