bahmnilab_url: "https://s3.ap-south-1.amazonaws.com/ocg-repos/lab_artifacts/bahmni-lab-89-96.noarch.rpm"
bahmni_lab_temp_files:
  - bahmni-lab.war
bahmni_lab:
  - config.rb
  - css
  - documentation
  - fonts
  - images
  - index.jsp
  - LICENSE
  - media
  - META-INF
  - pages
  - scripts
  - tree_images
  - WEB-INF
